[project]
name = "receptsite"
version = "0.1.0"
description = ""
authors = [
    {name = "Ruslan Romanov",email = "ruslan97_19972mail.ru"}
]

requires-python = ">=3.12"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
