# Generated by Django 5.1.6 on 2025-02-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('count_ingredients', models.CharField(blank=True, max_length=3)),
                ('ingredients', models.TextField(blank=True)),
                ('weight_ingredients_gramm', models.CharField(blank=True, max_length=3)),
                ('author', models.TextField()),
            ],
        ),
    ]
