# Generated by Django 5.1.6 on 2025-02-14 23:38

import recept.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0002_recept_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recept',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=recept.models.recept_preview_directory_path),
        ),
    ]
