# Generated by Django 5.1.6 on 2025-02-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0003_alter_recept_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recept',
            name='weight_ingredients_gramm',
            field=models.TextField(blank=True),
        ),
    ]
